### ISSUE TITLE
Some improvement ideas

### ISSUE THREAD

**Issue by klingtnet** [sharkdp/diskus#10]
Can you please allow to pass a path to dup?
The motivation behind this request is that it's pretty inconvenient to change my working directory only to know how much space it uses on disk. Even better, allow to pass an arbitrary number of paths and process them simultaneously. Also, please consider JSON output as mentioned in a comment [from this lobste.rs thread](https://lobste.rs/s/vh6uhw/minimal_fast_alternative_du_sh#c_hcak9b).

**Comment by sharkdp** [comment]
Thank you for your feedback.

> Can you please allow to pass a path to dup?

Please see #3.

> Also, please consider JSON output as mentioned in a comment [from this lobste.rs thread](https://lobste.rs/s/vh6uhw/minimal_fast_alternative_du_sh#c_hcak9b).

Can you please open a new ticket (it's hard to correctly track unrelated things in one ticket) and explain the motivation behind this? Thank you.

**Comment by sharkdp** [comment]
The first part is now supported in the latest version.
