### ISSUE TITLE
Export this project as a library

### ISSUE THREAD

**Issue by amilajack** [sharkdp/diskus#12]
Many other users and myself would find a lot of value in this library being exported as a library. Is this in the roadmap?

**Comment by sharkdp** [comment]
Thank you for your feedback. Right now, this is really just a very thin wrapper around the `ignore` crate. Maybe this could be of use to you?

**Comment by sharkdp** [comment]
Small update: after some updates, this is not true anymore. We now use a custom parallel directory walker.

**Comment by amilajack** [comment]
Would a PR for this be welcome?

**Comment by sharkdp** [comment]
Absolutely. I'd like to keep this within a single crate (and repository) though. Is that possible?

**Comment by amilajack** [comment]
Yea definitely! Cargo lets you publish both binaries and libs
