### ISSUE TITLE
No boilerplate copyright notice

### ISSUE THREAD

**Issue by Crestwave** [sharkdp/diskus#14]
As in `Copyright [yyyy] [name of copyright owner]`, which, as far as I know, is required to apply the Apache 2.0 license.

**Comment by sharkdp** [comment]
Thank you for your feedback.

I don't think that it is strictly necessary, see

* http://www.apache.org/dev/apply-license.html#copy-per-file
* https://softwareengineering.stackexchange.com/a/270098

I have added a License section in the README, though: https://github.com/sharkdp/diskus#license

**Comment by Crestwave** [comment]
Who should I list as the copyright owner(s), though? `2018 diskus developers`?

**Comment by sharkdp** [comment]
Yes. Thank you.
