### ISSUE TITLE
Please publish Cargo.lock with the crate

### ISSUE THREAD

**Issue by polyzen** [sharkdp/diskus#16]
`error: the lock file needs to be updated but --locked was passed to prevent this`

**Comment by sharkdp** [comment]
What exactly do you mean? The `Cargo.lock` file seems to be up-to-date, i.e. it does not change if I run `cargo build`.

**Comment by polyzen** [comment]
I see the lock file isn't shipped with the crate.

Looks like this would be needed:
https://github.com/rust-lang/cargo/issues/5654

**Comment by polyzen** [comment]
What do you think? I requested this from a bunch of projects (for reproducible builds) before realizing it was a bit more involved.

**Comment by sharkdp** [comment]
Sounds like a good idea to me, thank you. Let's add this.

**Comment by sharkdp** [comment]
Closing this for now, see #17

**Comment by polyzen** [comment]
> [Cargo will be changed to always include Cargo.lock in the .crate file if the package has binaries or examples.](https://github.com/rust-lang/cargo/issues/5654#issuecomment-497863987)

**Comment by sharkdp** [comment]
Thank you for the info. Happy to release a new version once this is implemented
