### ISSUE TITLE
Difference in size reported by `du -sh` and diskus

### ISSUE THREAD

**Issue by j605** [sharkdp/diskus#19]
In a directory with VM images, 
```sh
jagan@giant ~/s/diskus> cd ~/.vm
jagan@giant ~/.vm> du -sh
32G     .
jagan@giant ~/.vm> dup 
68.72 GB (68719480832 bytes)
```
Is this due to sparse files? The huge difference in the numbers can be misleading.

PS: Still using old binary. I was not able to compile it again after the name change. Getting this from rustc,
```rust
error[E0658]: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)                                                                        
  --> /home/jagan/.cargo/registry/src/github.com-1ecc6299db9ec823/term_size-0.3.1/src/lib.rs:16:1                                                                         
   |                                                                                                                                                                      
16 | extern crate libc;                                                                                                                                                   
   | ^^^^^^^^^^^^^^^^^^                                                                                                                                                   
```

**Comment by sharkdp** [comment]
> Is this due to sparse files? The huge difference in the numbers can be misleading.

Have you seen #11?

> I was not able to compile it again after the name change.

Which version of Rust are you using? Rust 1.29 is the minimum supported Rust version: https://github.com/sharkdp/diskus#via-cargo

**Comment by j605** [comment]
Sorry, I missed #11. We can close this then. Regarding rustc, I am using 1.30.1.

**Comment by sharkdp** [comment]
> Regarding rustc, I am using 1.30.1.

Strange. Could you please try to run `cargo clean` first and then post the full output of
```
cargo install -f
```
?

**Comment by j605** [comment]
I removed the cargo cache and recompiled it. I hit similar errors with other packages which implied it was not a problem with diskus. Thanks :)
