### ISSUE TITLE
Support resident size as well as apparent size or clarify description

### ISSUE THREAD

**Issue by ylluminarious** [sharkdp/diskus#25]
Currently, `diskus`'s description is misleading [as you explained here.](https://github.com/sharkdp/diskus/issues/11#issuecomment-435411963) It is actually not an alternative to `du -sh`, but to `du -sb`. I suggest that support be added for resident size (i.e., disk usage) in addition to apparent size. If you don't want to add support for this, please at least change the description and the README file to clarify that only apparent size is computed and not resident size.

**Comment by sharkdp** [comment]
Thank you for the feedback!

Yes, we should probably support both. Until somebody implements this, we should change the documentation, agreed. I currently don't have enough time for this project, but I'm happy to accept PRs.

**Comment by ylluminarious** [comment]
@sharkdp Thanks for the response. Unfortunately, I don't know Rust and I have a little too much on my plate right now to sit down and learn a new language. So I'm not in much of a position to give PRs myself. But thanks for at least agreeing to change the documentation, I appreciate it.

**Comment by sharkdp** [comment]
Fixed in [v0.6.0](https://github.com/sharkdp/diskus/releases/tag/v0.6.0)

**Comment by ylluminarious** [comment]
@sharkdp Thank you!
