### ISSUE TITLE
Please upgrade the version of libc in Cargo.lock

### ISSUE THREAD

**Issue by xctan** [sharkdp/diskus#45]
I'm trying to make diskus package for Arch RISC-V, but the old version (currently 0.2.62) of libc in Cargo.lock failed to compile on riscv64 architecture. This can be fixed by upgrading libc in Cargo.lock, so we can make PKGBUILD work without patching libc version before building.

**Comment by sharkdp** [comment]
Fixed. Released as https://github.com/sharkdp/diskus/releases/tag/v0.7.0
