### ISSUE TITLE
Calculate size for directory names passed as arguments

### ISSUE THREAD

**Issue by karanrajpal14** [sharkdp/diskus#5]
Hey, it would be great if I could pass directories as args and have dup calculate the size only for those directories. It's definitely easier than doing them separately and adding the results myself. What do you think?

**Comment by sharkdp** [comment]
Thank you for the feedback.

Please see #3.

**Comment by sharkdp** [comment]
This is now supported in the latest version. However, it only shows the aggregated result:
```
▶ diskus src ci 
16.44 KB (16441 bytes)
```

**Comment by karanrajpal14** [comment]
Thank you @sharkdp
