### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by njtierney** [sharkdp/diskus#6]
Hello! Thanks for writing this, looks super neat! :)

I had a problem installing this just now, perhaps I am missing something obvious, but just wanted to file this in case it is helpful

Details below, let me know if you would like more information :)
```
$ cargo install du-dup
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing du-dup v0.2.0
   Compiling crossbeam-utils v0.5.0
   Compiling semver-parser v0.7.0
   Compiling strsim v0.7.0
   Compiling nodrop v0.1.12
   Compiling rand_core v0.3.0
   Compiling cfg-if v0.1.6
   Compiling scopeguard v0.3.3
   Compiling memoffset v0.2.1
error: the struct `#[repr(align(u16))]` attribute is experimental (see issue #33626)
  --> /Users/ntie0001/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.5.0/src/cache_padded.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^

error: non-string literals in attributes, or string literals in top-level positions, are experimental (see issue #34981)
  --> /Users/ntie0001/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.5.0/src/cache_padded.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `crossbeam-utils`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `du-dup v0.2.0`, intermediate artifacts can be found at `/var/folders/mw/gj7418356js6s29x7wn8crfmljy4wh/T/cargo-install.rwrMN5HWFtwH`

Caused by:
  build failed
```

**Comment by sharkdp** [comment]
> Hello! Thanks for writing this, looks super neat! :)

Thank you for the feedback!

Which version of Rust are you using? This feature should have been stable for quite some time, judging by the time [the referenced ticket](https://github.com/rust-lang/rust/issues/33626) was closed.

**Comment by sharkdp** [comment]
Rust 1.29 and higher should work. I haven't tested anything before that.

**Comment by njtierney** [comment]
Ah yes, I should have checked the version of rust I was using - I was on `1.24.1`, which looks like it didn't have rustup, so I uninstalled with `brew uninstall rust`, and then used the instructions here: https://www.rust-lang.org/en-US/install.html to reinstall.

works great now, thanks for your help! :)

**Comment by sharkdp** [comment]
Thank you for the feedback!
