### ISSUE TITLE
Include in Homebrew

### ISSUE THREAD

**Issue by colindean** [sharkdp/diskus#7]
This is a great tool that I'd love to see included in Homebrew. However, it's not notable enough yet and too new.

When it is 30 days old and has one of: 

1. ≥ 30 watchers,
2. ≥ 30 forks, or 
3. ≥ 75 stars, _(most likely to qualify)_

it can be submitted for inclusion at [homebrew/homebrew-core](https://github.com/homebrew/homebrew-core).

**Comment by sharkdp** [comment]
I haven't even announced this project anywhere, but thank you very much for the feedback :smile:.

Let's first resolve the naming "issue" (#9) before we start packaging this.

**Comment by sharkdp** [comment]
The third condition is now met. If somebody adds this to Homebrew, please let me know. I'd be happy to add a corresponding section to the README.

**Comment by leonklingele** [comment]
@sharkdp I've opened https://github.com/Homebrew/homebrew-core/pull/35811

**Comment by sharkdp** [comment]
Thank you very much!

**Comment by colindean** [comment]
Damn, you beat me to the PR! I was just about to push up when someone interrupted me and pulled me away from my computer!

Edit: TBH your test is better than mine.

**Comment by leonklingele** [comment]
`brew install diskus`.

**Comment by colindean** [comment]
It's available so I'm closing this in great success 🏆

**Comment by sharkdp** [comment]
Awesome, thank you very much @leonklingele. We should also add a small section to the README.
