### ISSUE TITLE
license needs clarification

### ISSUE THREAD

**Issue by apotheon** [sharkdp/diskus#8]
Please clarify licensing.  I have not found anything indicating how you mean this to be licensed.  Is it MIT+Apache, or is it a standard "recipient chooses" dual licensing scheme where the recipent gets to decide which license to accept?

**Comment by sharkdp** [comment]
Thank you for asking. It is dual-licenced (MIT or Apache):

https://github.com/sharkdp/dup/blob/a4daa3439c083d2885a387bd7c7bc722bec12782/Cargo.toml#L6

Choose whichever you prefer.

**Comment by apotheon** [comment]
Thanks for clarifying that for me.

I would appreciate it if it was made clear in the README and/or the tops of the LICENSE files.  I'm not sure a slash in the cargo config file has established legal meaning.

**Comment by sharkdp** [comment]
Added a section in the README.

**Comment by apotheon** [comment]
Thanks!
